name: Deploy Portfolio

on:
  push:
    branches:
      - main  # This will trigger deployment on pushes to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the build environment.
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository.

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the Node.js version you need.

    - name: Install dependencies
      run: npm install  # Install the dependencies specified in package.json.

    - name: Build Portfolio
      run: npm run build  # Build your portfolio for production.

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main  # This will deploy to the 'gh-pages' branch.
        folder: build  # This is the directory where your built files are located.
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for authentication.
